swagger: "2.0"
info:
  title: Createam Demo application
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /api/dummy:
    get:
      summary: Returns request url in json ex \:"{"requestFrom":"http://request-url.example"}".
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
